packages:
  - packages/*
  - contracts/*

catalog:
  '@nomicfoundation/hardhat-ethers': ^3.1.3
  '@nomicfoundation/hardhat-network-helpers': ^1.1.2
  '@nomicfoundation/hardhat-toolbox': ^5.0.0
  '@openzeppelin/hardhat-upgrades': ^3.9.1
  dotenv: ^17.2.3
  ethers: ^6.16.0
  hardhat: ^2.28.0
  hardhat-contract-sizer: ^2.10.1
  typescript: ^5.9.3

linkWorkspacePackages: false

onlyBuiltDependencies:
  - keccak
  - secp256k1

overrides:
  cookie@<0.7.0: '>=0.7.0'
  tmp@<=0.2.3: '>=0.2.4'
