packages:
  - packages/*
  - contracts/*

linkWorkspacePackages: false

onlyBuiltDependencies:
  - keccak
  - secp256k1

catalog:
  "@nomicfoundation/hardhat-toolbox": "^5.0.0"
  "@nomicfoundation/hardhat-ethers": "^3.1.3"
  "@openzeppelin/hardhat-upgrades": "^3.9.1"
  "ethers": "^6.16.0"
  "hardhat": "^2.28.0"
  "hardhat-contract-sizer": "^2.10.1"
  "dotenv": "^17.2.3"
